<?php


namespace patterns\ChainOfResponsibility;


class ThirdHandler extends HandlerAbstract
{
    public function handle(Request $request): Response
    {
        echo "Third handler\n";

        return parent::handle($request); // TODO: Change the autogenerated stub
    }
}